# Generated by Django 3.1.5 on 2021-02-25 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_friendrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friendrequest',
            options={'verbose_name': 'Friend request', 'verbose_name_plural': 'Friend requests'},
        ),
        migrations.AlterUniqueTogether(
            name='friendrequest',
            unique_together={('from_user', 'to_user')},
        ),
    ]
